name: webview_flutter_plus
description: An extension of webview_flutter to load local HTML,CSS and Javascript from Assets or Strings and much more.

version: 0.4.7

homepage: https://github.com/Shahxad-Akram/webview_flutter_plus

environment:
  sdk: '>=3.2.3 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  webview_flutter: ^4.8.0
  mime: ^1.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0